controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation


index:
    path: /main
    controller: App\Controller\MainController::index


post:
    path: /post
    controller: App\Controller\PostController::index

nbp:
    path: /nbp
    controller: App\Controller\NbpController::index